### ISSUE TITLE
Change realm should mantain scenes with same entity id

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/godot-explorer#107]
When we change realm, we're cleaning all the scenes and loading them again.

The correct behaviour should be to maintain the scenes with the same entity id.

Example, execute the following commands in the Godot Explorer:
- /changerealm https://peer.decentraland.org
- /changerealm https://peer.kyllian.me

^ the content should be the same, so no scene reloading is needed here, just change the comms adapter

**Comment by kuruk-mm** [comment]
There is no need for doing this. Just reloading the scene it's ok.

**Comment by leanmendoza** [comment]
I'm not completely sure about it, the use case was for loading different catalyst you used to change only the comms
