### ISSUE TITLE
Web3 implementation (Godot)

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/godot-explorer#108]
Basic implementation of Web3 on Godot.
- Enable log in with Metamask, Wallet Connect or Magic (social login)
- Implement Ethereum Controller for scenes to request transaction and/or have a ethereum provider

**Comment by leanmendoza** [comment]
Closed by:
- https://github.com/decentraland/godot-explorer/pull/105
- https://github.com/decentraland/godot-explorer/pull/122
- https://github.com/decentraland/godot-explorer/pull/121

Working on Desktop and Mobile
