### ISSUE TITLE
Focus and voice chat button

### ISSUE THREAD

**Issue by leanmendoza** [decentraland/godot-explorer#138]
There were focus bugs in the explorer main UI, so Voice Chat button was removed temporarily since https://github.com/decentraland/godot-explorer/commit/91e33450602ccd23ccc4c8c4760059ccc5a4077f

This issue is an item from implementing UI as it is supposed to be

**Comment by kuruk-mm** [comment]
Closed by #226

**Comment by kuruk-mm** [comment]
Duplicated from https://github.com/decentraland/godot-explorer/issues/182
