### ISSUE TITLE
(82, 0) clap-meter

### ISSUE THREAD

**Issue by sdilauro** [decentraland/godot-explorer#281]
- [x] The gauge rises faster in Godot.
- [ ] clapping emotes (icons) are not displayed on the character when clapping.

[Screencast from 23-02-24 10:16:05.webm](https://github.com/decentraland/godot-explorer/assets/22157752/427e0be4-3a15-4024-852c-90be6c4d856a)

**Comment by kuruk-mm** [comment]
Fixed due to spritesheet test (not know exactly which PR fixed it)
