### ISSUE TITLE
(78, -4) smoke

### ISSUE THREAD

**Issue by sdilauro** [decentraland/godot-explorer#286]
Smoke is a little stronger in Godot, maybe this isn't an issue.

G:
![image](https://github.com/decentraland/godot-explorer/assets/22157752/650f8c44-0b08-4065-9659-1b44d052a08e)

F:
![image](https://github.com/decentraland/godot-explorer/assets/22157752/a7d7e805-ef56-49b3-859d-a93d1e63ac65)

**Comment by kuruk-mm** [comment]
Visual can differ between explorers
