### ISSUE TITLE
(78, -1) zombie-attack

### ISSUE THREAD

**Issue by sdilauro** [decentraland/godot-explorer#289]
The zombies don't change to attack animation when are close to the character in Godot.

**Comment by kuruk-mm** [comment]
Looks like it's related to https://github.com/decentraland/sdk/issues/903 too

**Comment by kuruk-mm** [comment]
> Looks like it's related to [decentraland/sdk#903](https://github.com/decentraland/sdk/issues/903) too

Reason, it was fixed on the scene-side
