### ISSUE TITLE
(72, -10) power-cube

### ISSUE THREAD

**Issue by sdilauro** [decentraland/godot-explorer#296]
- [ ] Character doesn't pick up the card when walks on it.

**Comment by kuruk-mm** [comment]
It must jump. We should check the colliders.

And maybe it's related to: https://github.com/decentraland/sdk/issues/903

and it's a scene issue

**Comment by kuruk-mm** [comment]
Confirmed. It's due to https://github.com/decentraland/sdk/issues/903
