### ISSUE TITLE
(81, -2) droid-scene

### ISSUE THREAD

**Issue by sdilauro** [decentraland/godot-explorer#299]
- [x] Character can climb the rock in Foundation. That is possible eventually in Godot, but very difficult to get.

![image](https://github.com/decentraland/godot-explorer/assets/22157752/a9ca070a-10b1-4f57-b8e4-d8332566674e)

**Comment by kuruk-mm** [comment]
This is related to how collisions and the avatar movement works.

That is not a bug. It's an enhancement that we can do in the future. But not planned.
