### ISSUE TITLE
(76, -5) wearables-scanner

### ISSUE THREAD

**Issue by sdilauro** [decentraland/godot-explorer#302]
the house 3D model is loaded but with errors (some walls don't appear and the door is open) in Godot.

![image](https://github.com/decentraland/godot-explorer/assets/22157752/211ad956-4cef-456d-a270-8be15a1ce4d1)

**Comment by kuruk-mm** [comment]
Looks like this error is because the file name is too large

```
Error on fetch gltf: Error downloading content http://127.0.0.1:8000/content/contents/b64-L2hvbWUva3VydWsvUHJvamVjdHMvZGVjZW50cmFsYW5kL3NkazctZ29lcmxpLXBsYXphL1dlYXJhYmxlcy1zY2FubmVyL2Fzc2V0cy9idWlsZGVyL3N0b25lX2JyaWNrX3dpbmRvd193aXRoX3N0YWluZWRfZ2xhc3MvTW9kdWxlX1N0b25lX1N0cmFpZ2h0X1dpbmRvd18wMi9Nb2R1bGVfU3RvbmVfU3RyYWlnaHRfV2luZG93XzAyLmdsYg== (/home/kuruk/.local/share/godot/app_userdata/Decentraland Godot Rust/content/b64-L2hvbWUva3VydWsvUHJvamVjdHMvZGVjZW50cmFsYW5kL3NkazctZ29lcmxpLXBsYXphL1dlYXJhYmxlcy1zY2FubmVyL2Fzc2V0cy9idWlsZGVyL3N0b25lX2JyaWNrX3dpbmRvd193aXRoX3N0YWluZWRfZ2xhc3MvTW9kdWxlX1N0b25lX1N0cmFpZ2h0X1dpbmRvd18wMi9Nb2R1bGVfU3RvbmVfU3RyYWlnaHRfV2luZG93XzAyLmdsYg==): RequestResponseError { id: 99, error_message: "File name too long (os error 36)" }
```

**Comment by sdilauro** [comment]
In another realm (`https://sdk-team-cdn.decentraland.org/ipfs/goerli-plaza-update-asset-pack-lib`) the model loads fine but with the door opened permanently when it should open only with the specific wearable.
![image](https://github.com/decentraland/godot-explorer/assets/22157752/f75e7a45-1e45-4f83-9bcd-50389d724fcd)

**Comment by kuruk-mm** [comment]
Fixed on the realm side
