### ISSUE TITLE
(80, -3) simple-npc

### ISSUE THREAD

**Issue by sdilauro** [decentraland/godot-explorer#305]
- [ ] Dialogue with the robot dialogue doesn't show interactions (E or F) in Godot.
![image](https://github.com/decentraland/godot-explorer/assets/22157752/0fdfcfd3-cc0d-47df-89a4-a4bb2210155e)
![image](https://github.com/decentraland/godot-explorer/assets/22157752/b4fa41f8-6b56-40f8-ad16-eb207eeed96d)

- [ ] Dog doesn't show any dialogue when the character interacts in Godot.
![image](https://github.com/decentraland/godot-explorer/assets/22157752/25983be6-84b4-4def-8a40-7898fa3ac559)
![image](https://github.com/decentraland/godot-explorer/assets/22157752/78246290-efeb-432f-9658-f6ebc55b91d2)

**Comment by kuruk-mm** [comment]
Fixed
