### ISSUE TITLE
(79, 4) block-fountain

### ISSUE THREAD

**Issue by sdilauro** [decentraland/godot-explorer#319]
- [ ] The fountains should be synchronized among all clients.

[Screencast from 22-02-24 18:38:38.webm](https://github.com/decentraland/bevy-explorer/assets/22157752/76692a0d-1f29-45ca-b92c-27bfdb080a1a)

**Comment by kuruk-mm** [comment]
Fixed by https://github.com/decentraland/unity-renderer/pull/6156
Now syncs correctly with Foundation
