### ISSUE TITLE
(73, -8) shark-animation - (76, -9) Hummingbirds

### ISSUE THREAD

**Issue by sdilauro** [decentraland/godot-explorer#328]
- [ ] Shark doesn't show any interaction.
![image](https://github.com/decentraland/godot-explorer/assets/22157752/ecd38ed9-df2f-4db1-860f-0f936737fcf1)

- [ ] Interaction is only possible on the poster (it is also possible on the tree in the foundation client)

[Screencast from 28-02-24 12:22:28.webm](https://github.com/decentraland/godot-explorer/assets/22157752/e41c42cf-b892-4e53-a7e0-dde8213a34d8)

**Comment by kuruk-mm** [comment]
What about the Tree Collision? It is the same as the Foundation? @sdilauro

**Comment by sdilauro** [comment]
The character doesn't collide with any model in the scene in any clients
Foundation:
[Screencast from 28-02-24 15:19:02.webm](https://github.com/decentraland/godot-explorer/assets/22157752/c8dbb5d7-fe5b-4a84-846b-8a9ab2d66ed9)

Godot:
[Screencast from 28-02-24 15:19:51.webm](https://github.com/decentraland/godot-explorer/assets/22157752/1d22154f-ac39-4ad7-88c1-c789888344cf)

**Comment by kuruk-mm** [comment]
Fixed
