### ISSUE TITLE
Interactions don't appear when resize windows

### ISSUE THREAD

**Issue by sdilauro** [decentraland/godot-explorer#331]
The cube's interaction is able only if the first-person camera is enabled when resizing to fullscreen:

[Screencast from 28-02-24 12:37:28.webm](https://github.com/decentraland/godot-explorer/assets/22157752/4c75b15e-ac3a-4acc-8759-0c0ba9f653fc)

zombie-shooter example:

[Screencast from 28-02-24 15:40:06.webm](https://github.com/decentraland/godot-explorer/assets/22157752/bea9514b-8a72-4c4f-b9f5-edacffcd6270)

sliding-door example:

[Screencast from 28-02-24 16:09:12.webm](https://github.com/decentraland/godot-explorer/assets/22157752/1cf09d40-b42b-480d-8bfe-5b3408e857f3)

coconut-shy example:

[coconut-shy.webm](https://github.com/decentraland/godot-explorer/assets/22157752/0f0c6537-102b-41ee-8db5-
b94f14f3349c)

**Comment by leanmendoza** [comment]
Desktop problem, solved in the bugfixing stage
