### ISSUE TITLE
(79, 1) show-manager-example

### ISSUE THREAD

**Issue by sdilauro** [decentraland/godot-explorer#353]
- [ ] Shows aren't synchronized with other clients.
- [ ] Nobody walks on the pasarell. **** (one time works properly)
- [ ] Laser plane doesn't have a transparent background

[show-manager-example.webm](https://github.com/decentraland/godot-explorer/assets/22157752/2f16309a-9f53-427e-80b4-5082cbffefb4)

**Comment by kuruk-mm** [comment]
Reason: https://github.com/decentraland/godot-explorer/issues/403
