### ISSUE TITLE
UX improvement when loading new scenes

### ISSUE THREAD

**Issue by leanmendoza** [decentraland/godot-explorer#425]
Sometimes, while you're walking inside a scene, the loading of other scenes introduces hiccups, and this might happen as well with the unloading.
This could be solved by fixing in advance the scenes that can be loaded while you're inside the one scene. The algorithm can maximize the scenes available or not or maybe it could be settings or set when the memory and CPU are enough.
So the hiccup is only reserved when you really change the scene

**Comment by kuruk-mm** [comment]
In the ResourceLoader we increase/decrease the amount of parallel downloads when you're in the LoadingScreen or not. That should improve a bit.
