### ISSUE TITLE
Implement Wallet Connect and Magic natively (Godot)

### ISSUE THREAD

**Issue by leanmendoza** [decentraland/godot-explorer#432]
- [ ] WalletConnect
  - [ ] Android
    - [ ] tested on Mobile
    - [ ] tested on VR
  - [ ] iOS 
- [x] Magic
  - [x] Android
    - [x] tested on Mobile
    - [ ] tested on VR
  - [ ] iOS

**Comment by kuruk-mm** [comment]
The implementation of Magic went well. But the Magic SDK it has a lot of bugs, that makes it unusable.

We had conversations with Magic, and they recommend us to use the React JS implementation. Which requires a integration with a WebBrowser. We proposed to implement it in the next grant, also with the integration for Wallet Connect. More details: https://decentraland.org/governance/proposal/?id=8ce24f4d-ed98-421b-a04e-dd71876bf9a2
