### ISSUE TITLE
`Condition "det == 0" is true` at 81, -6

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/godot-explorer#75]
The Godot Engine spams the error `Condition "det == 0" is true.` every frame.

This is happening in the Goerli Plaza Scene in 81, -6

Scene code:
https://github.com/decentraland/sdk7-goerli-plaza/tree/main/lazy-loading

Probably it's happening because it's using `scale(0,0,0)` to hide the scenes.

```typescript
export function hideScene(scene: Entity) {
  Transform.get(scene)
  Transform.createOrReplace(scene, { scale: Vector3.create(0, 0, 0) })
}

export function showScene(scene: Entity) {
  Transform.get(scene)
  Transform.createOrReplace(scene, { scale: Vector3.create(1, 1, 1) })
}
```

**Comment by leanmendoza** [comment]
fixed https://github.com/decentraland/godot-explorer/pull/127
